# Generated by Django 6.0 on 2025-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_group_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
